#include "src/game/envfx_snow.h"

const GeoLayout shadow_sink_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -85, 0, shadow_sink_Bone_mesh),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 47, 102, shadow_sink_armbase_mesh),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, shadow_sink_armmid_skinned),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 55, 0, shadow_sink_armmid_mesh),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, shadow_sink_armwrist_skinned),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 72, 0, shadow_sink_armwrist_mesh),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, shadow_sink_hand_skinned),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 52, 0, shadow_sink_hand_mesh),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, -110, 47, -44, shadow_sink_armbase_001_mesh),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, shadow_sink_armmid_001_skinned),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 55, 0, shadow_sink_armmid_001_mesh),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, shadow_sink_armwrist_001_skinned),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 72, 0, shadow_sink_armwrist_001_mesh),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, shadow_sink_hand_001_skinned),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 52, 0, shadow_sink_hand_001_mesh),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 70, 47, -85, shadow_sink_armbase_002_mesh),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, shadow_sink_armmid_002_skinned),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 55, 0, shadow_sink_armmid_002_mesh),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, shadow_sink_armwrist_002_skinned),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 72, 0, shadow_sink_armwrist_002_mesh),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, shadow_sink_hand_002_skinned),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 52, 0, shadow_sink_hand_002_mesh),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, shadow_sink_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
