extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern const GeoLayout bob_area_2_geo[];
extern const GeoLayout bob_area_2[];
extern const Collision bob_area_2_collision[];
extern const MacroObject bob_area_2_macro_objs[];
extern const GeoLayout bob_area_3_geo[];
extern const GeoLayout bob_area_3[];
extern const Collision bob_area_3_collision[];
extern const MacroObject bob_area_3_macro_objs[];
extern Vtx bob_dl_Plane_mesh_vtx_0[9];
extern Gfx bob_dl_Plane_mesh_tri_0[];
extern Vtx bob_dl_Plane_mesh_vtx_1[68];
extern Gfx bob_dl_Plane_mesh_tri_1[];
extern Vtx bob_dl_Plane_002_mesh_vtx_0[28];
extern Gfx bob_dl_Plane_002_mesh_tri_0[];
extern Vtx bob_dl_Plane_002_mesh_vtx_1[54];
extern Gfx bob_dl_Plane_002_mesh_tri_1[];
extern Vtx bob_dl_Cube_mesh_vtx_0[72];
extern Gfx bob_dl_Cube_mesh_tri_0[];
extern Vtx bob_dl_Plane_001_mesh_vtx_0[61];
extern Gfx bob_dl_Plane_001_mesh_tri_0[];
extern Vtx bob_dl_Plane_001_mesh_vtx_1[29];
extern Gfx bob_dl_Plane_001_mesh_tri_1[];
extern Vtx bob_dl_Plane_001_mesh_vtx_2[13];
extern Gfx bob_dl_Plane_001_mesh_tri_2[];
extern Vtx bob_dl_Plane_003_mesh_vtx_0[9];
extern Gfx bob_dl_Plane_003_mesh_tri_0[];
extern Vtx bob_dl_Plane_003_mesh_vtx_1[68];
extern Gfx bob_dl_Plane_003_mesh_tri_1[];
extern Vtx bob_dl_Plane_004_mesh_vtx_0[28];
extern Gfx bob_dl_Plane_004_mesh_tri_0[];
extern Vtx bob_dl_Plane_004_mesh_vtx_1[54];
extern Gfx bob_dl_Plane_004_mesh_tri_1[];

extern Gfx bob_dl_Plane_mesh[];
extern Gfx bob_dl_Plane_002_mesh[];
extern Gfx bob_dl_Cube_mesh[];
extern Gfx bob_dl_Plane_001_mesh[];
extern Gfx bob_dl_Plane_003_mesh[];
extern Gfx bob_dl_Plane_004_mesh[];
extern Gfx bob_dl_material_revert_render_settings[];

