#include "src/game/envfx_snow.h"

const GeoLayout sa_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(6, -3150, 0, 4438, sa_dl_Grass_001_mesh_layer_6),
		GEO_TRANSLATE_NODE_WITH_DL(1, -3150, 0, 4438, sa_dl_Grass_002_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(6, sa_dl_Grass_002_mesh_layer_6),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(6, -3150, 0, 4438, sa_dl_Grass_003_mesh_layer_6),
		GEO_TRANSLATE_NODE_WITH_DL(6, -3150, 0, 4438, sa_dl_Grass_004_mesh_layer_6),
		GEO_TRANSLATE_NODE_WITH_DL(1, -3150, 0, 4438, sa_dl_Sand_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(6, sa_dl_Sand_mesh_layer_6),
			GEO_DISPLAY_LIST(4, sa_dl_Sand_mesh_layer_4),
			GEO_DISPLAY_LIST(2, sa_dl_Sand_mesh_layer_2),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, sa_dl_Sand_mesh),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(5, -3150, 0, 4438, sa_dl_Sand_001_mesh_layer_5),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(6, sa_dl_Sand_001_mesh_layer_6),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(1, -3150, -379, 4438, sa_dl_Skybox_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(5, -3150, 0, 4438, sa_dl_Water_mesh_layer_5),
		GEO_TRANSLATE_NODE_WITH_DL(5, -3150, -379, 4438, sa_dl_Water_2_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sa_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND(BACKGROUND_OCEAN_SKY, geo_skybox_main),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, sa_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(4, sa_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sa_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, sa_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, sa_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, sa_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, sa_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
